# Generated by Django 5.0.2 on 2024-03-06 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
