# Generated by Django 5.0.2 on 2024-03-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('Happening Now', 'Happening Now'), ('Upcoming', 'Upcoming'), ('DONE', 'DONE')], default='Upcoming', max_length=30),
        ),
    ]
