# Generated by Django 5.0.2 on 2024-03-06 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_location_alter_events_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
