# Generated by Django 5.0.2 on 2024-03-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='status',
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
