# Generated by Django 5.0.2 on 2024-03-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_events_status_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=12, null=True),
        ),
    ]
