# Generated by Django 5.0.2 on 2024-03-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/OIG3.jpeg', null=True, upload_to='covers/'),
        ),
    ]
